# Generated by Django 5.1.3 on 2025-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_purchaseorder_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionupdate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionupdate',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionupdate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
